# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickPyQGIS
                                 A QGIS plugin
 QuickPyQGIS is a QGIS plugin that streamlines PyQGIS scripting by generating ready-to-use code snippets directly within the QGIS interface. With actions integrated into the UI, it allows users to quickly populate the Python Console with relevant PyQGIS code, enhancing productivity and simplifying script development.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-02
        copyright            : (C) 2024 by Julius Tóth
        email                : juliustoth1996@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load QuickPyQGIS class from file QuickPyQGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .quick_pyqis import QuickPyQGIS
    return QuickPyQGIS(iface)
